# 100 ejercicios numpy

In [1]:
#importar numpy
import numpy as np

In [2]:
#imprimir la configuracion y version de numpy
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/pope/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/pope/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/pope/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\li

In [3]:
#Crear un vector nulo size10
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#Obtener documentacion de numpy desde command line
python -c "import numpy; numpy.info(numpy.add)"

In [4]:
#Crear un vector nulo size10 con el quinto elemento de valor 1
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
#Crear un vector con valores en rango 10 a 49
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
#Vector revertido
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [7]:
#Crear matriz 3x3 con valores de 0 a 8
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
#Encontrar indices de elementos no-zero
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [9]:
#Crear matriz indentidad 3x3
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#Crear 3 matrices 3x3 con valores aleatorios
Z = np.random.random((3,3,3))
print(Z)

[[[0.79308006 0.48966526 0.48669156]
  [0.17065228 0.62533645 0.67765111]
  [0.96077972 0.05771066 0.39229995]]

 [[0.89647304 0.48836133 0.80954868]
  [0.74591682 0.45338004 0.61871788]
  [0.19834928 0.16600653 0.83943695]]

 [[0.88565024 0.73619191 0.09527765]
  [0.50303664 0.71576381 0.95633021]
  [0.99074815 0.91997814 0.16633299]]]


In [11]:
#Crear una matriz 10x10 con valores aleatorios y encontrar el minimo y el maximo
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0015788701239920488 0.9934655482251042


In [12]:
#Crear vector aleatorio size30 y calcular la media
Z = np.random.random(30)
m = Z.mean()
print(m)

0.49730489987108367


In [13]:
#Crear matriz 2d con 1 en los bordes y 0 en el interior
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [14]:
#Resultado de la expresion:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

In [15]:
#Crear matriz 5x5 con valores 1,2,3,4 debajo de la diagonal
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [16]:
#Crear matriz 8x8 y rellenarlo con un patron de damas
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [17]:
#Descubrir indice de elemento numero 100 en matriz (6,7,8)
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [18]:
#Crear tablero de damas 8x8 con la funcion tile
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [19]:
#Normalizar una matriz aleatoria 5x5
Z = np.random.random((5,5))
Zmin, Zmax = Z.min(), Z.max()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.64857548 0.88911683 0.72938067 0.74475865 0.11453411]
 [0.34359553 0.97278133 0.         0.58461649 0.57572735]
 [0.56572058 0.53574846 1.         0.37308851 0.7742935 ]
 [0.1339215  0.53655903 0.79352339 0.92377749 0.7171838 ]
 [0.20373041 0.22195804 0.48086207 0.09969492 0.71134124]]


In [20]:
#Crear dtype personalizado que describe un color como un byte(RGBA)
color = np.dtype([("r",np.ubyte,1),
                 ("g",np.ubyte,1),
                 ("b",np.ubyte,1),
                 ("a",np.ubyte,1)])
color

C:\Users\pope\anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [21]:
#Multiplicar matriz 5x3 por matriz 3x2
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [22]:
#Dada una matriz 1D, hacer negativos todos los elementos que estan entre 3 y 8
Z = np.arange(11)
Z[(3<Z) & (Z<=8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [23]:
#Resultado del scrip?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#Cual de estas expresiones es valida?
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [24]:
#Resultado de las siguientes expresiones?
print(np.array(0) // np.array(0))
print(np.array(0) // np.array(0.))
print(np.array(0) / np.array(0))
print(np.array(0) / np.array(0.))

0
nan
nan
nan


C:\Users\pope\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  
C:\Users\pope\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\pope\anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.
C:\Users\pope\anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """


In [25]:
#Cómo redondear desde cero una matriz flotante
Z = np.random.uniform(-10,+10,10)
print(np.trunc(Z + np.copysign(0.5, Z)))

[ -7.   6.   5.  -1.   3.  -2.  -9.   3.  -5. -10.]


In [26]:
#Extraer la parte entera de una matriz aleatoria utilizando 5 métodos diferentes
Z = np.random.uniform(0,10, 10)
print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[0. 6. 4. 8. 5. 8. 7. 9. 9. 9.]
[0. 6. 4. 8. 5. 8. 7. 9. 9. 9.]
[0. 6. 4. 8. 5. 8. 7. 9. 9. 9.]
[0 6 4 8 5 8 7 9 9 9]
[0. 6. 4. 8. 5. 8. 7. 9. 9. 9.]


In [27]:
#Crear una matriz 5x5 con los valores de las filas entre 0 y 4
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [28]:
#Considerar una función generadora que genera 10 enteros y usarla para construir una matriz
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float, count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [29]:
#Crear un vector size10 con valores entre 0 y 1, ambos excluidos
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [30]:
#Crear vector aleatorio size10 y ordenarlo
Z = np.random.random(10)
Z.sort()
print(Z)

[0.06694406 0.13341303 0.14690582 0.16186947 0.2221476  0.31668108
 0.80416527 0.80887689 0.82096635 0.98883188]


In [31]:
#Sumar una matriz mas rapido que np.sum
Z = np.arange(10)
np.add.reduce(Z)

45

In [32]:
#Considerar dos matrices aleatorias A y B, comprobar si son iguales
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [34]:
#Hacer una matriz inmutable(solo lectura)
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [ ]:
#Considerar una matriz aleatoria 10x2 representando coordenadas cartesianas, transformarla en coordenadas polares
Z = np.random.random((10,2))
X, Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y, X)
print(R)
print(T)

In [ ]:
#Crear un vestor aleatorio size 10 y cambiar el valor maximo por 0
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

In [ ]:
#Crear una matrizestructurada con x e y coordenadas cubriendo el area [0,1]x[0,1]
Z = np.zeros((10,10), [('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10), np.linspace(0,1,10))
print(Z)

In [ ]:
#Dadas dos matrices, X e Y, contruir una matriz Cauchy (Cij = 1/(xi-yj))
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

In [ ]:
#Imprimir el minimo y el maximo valor de cada valor tipo escalar de numpy
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

In [35]:
#imprimir todos los valores de una matriz
np.set_printoptions(threshold=0)
Z = np.zeros((25,25))
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [36]:
#Encontrar el valor mas cercano en una matriz
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

63


In [37]:
#Crear una matriz estructurada representando la posicion (x,y) y  un color(r,g,b)
Z = np.zeros(10, [('position', [('x', float, 1), ('y', float, 1)]),
                 ('color', [('r', float, 1), ('g', float, 1), ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ... ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\pope\anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  This is separate from the ipykernel package so we can avoid doing imports until


In [38]:
#considerar vercotr aleatorio (10,2) representando coordenadas, encontrar las distancias punto por punto
Z = np.random.random((10,2))
X, Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt(X-X.T)**2 + (Y-Y.T)**2
print(D)

import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

C:\Users\pope\anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in sqrt
  after removing the cwd from sys.path.


[[0.                nan        nan ...        nan        nan        nan]
 [0.31218978 0.         0.52384581 ...        nan        nan 0.10126993]
 [0.24423554        nan 0.         ...        nan        nan        nan]
 ...
 [0.84616281 0.47578093 1.26502737 ... 0.                nan 0.72376535]
 [0.89045551 0.53977145 1.23918071 ... 0.10482266 0.         0.73809353]
 [0.31858571        nan 0.27822315 ...        nan        nan 0.        ]]
[[0.         0.76876051 0.96680845 ... 0.80957308 1.09632206 0.12377083]
 [0.76876051 0.         0.35650701 ... 0.49696568 0.32790835 0.80177445]
 [0.96680845 0.35650701 0.         ... 0.30242454 0.3613409  1.03577101]
 ...
 [0.80957308 0.49696568 0.30242454 ... 0.         0.64410689 0.90490401]
 [1.09632206 0.32790835 0.3613409  ... 0.64410689 0.         1.12858482]
 [0.12377083 0.80177445 1.03577101 ... 0.90490401 1.12858482 0.        ]]


In [39]:
#Convertir un float en integer
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)

In [40]:
#Equivalente a enumerar en matrices numpy
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [41]:
#Aleatoriamente emplazar p elementos en una matriz 2D
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)

In [42]:
#Generar matriz gaussiana generica 2D
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D-mu)**2 / (2.0 * sigma**2)))
print(G)

[[0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 ...
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]]


In [43]:
#Restar la media de cada fila en una matriz
X = np.random.rand(5,10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.01604182  0.27115853 -0.27110248 ...  0.10108138 -0.30000099
   0.13867061]
 [-0.14598766  0.02872241  0.16298462 ...  0.05451346 -0.4307702
   0.22421166]
 [ 0.31515189  0.08385037  0.17033104 ...  0.13453306  0.14189437
  -0.09718003]
 [-0.19488174  0.02930179  0.13632279 ...  0.02762111  0.32960765
   0.21084008]
 [ 0.47971934 -0.22565734  0.01193099 ...  0.05669548 -0.31474107
  -0.33756323]]


In [44]:
#Ordenar una matriz por cada columna
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[2 8 0]
 [7 5 1]
 [0 6 5]]
[[7 5 1]
 [0 6 5]
 [2 8 0]]


In [45]:
#Saber si una matriz 2D tiene columnas nulas
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


In [46]:
#Encontrar el valor mas cernano en una raiz dado un valor
Z = np.random.uniform(0,1, 10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.48916024379552425


In [47]:
#Crear una clase matriz que tiene un atributo de nombre
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [48]:
#Considerar un vector dado, como sumar 1 a cada elemento indexado por un segundo vector
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 6. 2. ... 8. 1. 1.]


In [49]:
#Como acumular elementos de un vector X a una matriz F basado en una lista indice I
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. ... 0. 0. 3.]


In [50]:
#Considerar una imagen (w,h,3) de (dtype=ubyte), computar el numero de colores unicos
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 + I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


In [51]:
#Consierar una matriz de cuatro dimensiones, como obtener la suma de los dos ultimos ejes de una vez
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[64 57 60 45]
 [73 75 46 68]
 [57 48 47 67]]


In [52]:
#Considerar un vector unidimensional, como computar las medias de los subconjuntos de D usando un vector S describiendo los indices del subconjunto
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.52489548 0.59010587 0.42656857 ... 0.52391537 0.52863984 0.66213484]


#Obtener la diagonal de un producto
# version lenta
np.diag(np.dot(A, B))
# version rapida
np.sum(A * B.T, axis=1)
# version ultrarapida
np.einsum("ij,ji->i", A, B)

In [53]:
#Considerar el vector [1,2,3,4,5], Como construir un nuevo vector con 3 ceros consecutivos  entre cada valor
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. ... 0. 0. 5.]


In [54]:
#Considerar una matriz (5,5,3), como multiplicarla x una matriz (5,5)
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A*B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [55]:
#Como intercambiar dos filas de una matriz
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [56]:
#Considerar un conjunto de 10 tripletas describiendo 10 triangulos(con vertices compartidos), encontrar el conjunto unico de segmentos que componen todos los triangulos
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2, axis=1), -1, axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view(dtype=[('p0',F.dtype), ('pl',F.dtype)])
G = np.unique(G)
print(G)

[( 3, 15) ( 3, 50) ( 3, 70) ... (70, 73) (74, 93) (88, 99)]


In [57]:
#Dada una matriz C que es bincount, como producir una matriz A  tal que np.bincount(A)==C
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)),C)
print(A)

[1 1 2 ... 4 4 6]


In [58]:
#Computar las medias usando una ventana deslizante sobre una matriz
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:]/n

Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3. ... 16. 17. 18.]


In [59]:
#Considerar una matriz unidimensional Z, construir una matriz bidimensional cuya primera fila sea(Z[0],Z[1],Z[2]) y cada subsecuente fila sea aumentado un indice
from numpy.lib import stride_tricks
def rolling(a, windows):
    shape = (a.size - windows + 1, windows)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 ...
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [60]:
#Negar un booleano, o cambiar el signo de un float
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.13736296,  0.27224502, -0.45720076, ..., -0.63433061,
        0.21704565, -0.59887489])

In [61]:
#Considerar dos conjuntos de puntos P0,P1 describiendo lineas y un punto p, computar las distancia de las lineas al punto
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1])/L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(1,2))
print(distance(P0, P1, p))

[ 5.4516963   9.35301619 16.84074694 ... 14.64269063 11.70947288
  9.19134252]


In [62]:
#Considerar dos conjuntos de puntos P0,P1 describiendo lineas y un conjunto de puntos P, computar las distancia de las lineas al punto
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(10,2))
print (np.array([distance(P0,P1,p) for p_i in p]))

[[ 7.90716184  4.80798507 13.13544409 ...  2.73384612  0.40562281
   0.09732659]
 [ 7.90716184  4.80798507 13.13544409 ...  2.73384612  0.40562281
   0.09732659]
 [ 7.90716184  4.80798507 13.13544409 ...  2.73384612  0.40562281
   0.09732659]
 ...
 [ 7.90716184  4.80798507 13.13544409 ...  2.73384612  0.40562281
   0.09732659]
 [ 7.90716184  4.80798507 13.13544409 ...  2.73384612  0.40562281
   0.09732659]
 [ 7.90716184  4.80798507 13.13544409 ...  2.73384612  0.40562281
   0.09732659]]


In [63]:
#considerar una matriz arbitraria, escribir una funcion que extraiga una subparte con una forma fija y centrarlo a un elemento dado
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill = 0
position = (1,1)
R = np.ones(shape, dtype=Z.dtype)*fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop = (P+Rs//2)+Rs%2
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[0 8 2 ... 4 8 4]
 [7 4 0 ... 5 0 2]
 [9 0 1 ... 3 2 9]
 ...
 [8 4 8 ... 8 3 8]
 [9 8 5 ... 6 8 0]
 [8 5 0 ... 1 2 0]]
[[0 0 0 0 0]
 [0 0 8 2 5]
 [0 7 4 0 0]
 [0 9 0 1 4]
 [0 6 1 8 7]]


C:\Users\pope\anaconda3\lib\site-packages\ipykernel_launcher.py:20: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [64]:
#Considerar un vector Z, tranformarlo en una matriz Z
Z = np.arange(1,15, dtype=uint32)
R = stride_tricks.as_strided(Z, (11,4), (4,4))
print(Z)
print(R)

[ 1  2  3 ... 12 13 14]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 ...
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [65]:
#Computar el rank de una matriz
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) #Singular Value Decomposition
rank = np.sum(S>1e-10)
print(rank)

10


In [66]:
#Encontrar el valor mas frecuente en una matriz
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

4


In [67]:
#Extraer todos los bloques contiguos 3x3 de una matriz 10x10
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i,j,n,n), strides=Z.strides + Z.strides)
print(C)

[[[[4 1 4]
   [1 3 0]
   [0 1 2]]

  [[1 4 2]
   [3 0 1]
   [1 2 2]]

  [[4 2 3]
   [0 1 0]
   [2 2 3]]

  ...

  [[4 1 4]
   [0 3 1]
   [3 4 3]]

  [[1 4 2]
   [3 1 1]
   [4 3 2]]

  [[4 2 2]
   [1 1 2]
   [3 2 0]]]


 [[[1 3 0]
   [0 1 2]
   [4 1 2]]

  [[3 0 1]
   [1 2 2]
   [1 2 2]]

  [[0 1 0]
   [2 2 3]
   [2 2 2]]

  ...

  [[0 3 1]
   [3 4 3]
   [4 0 1]]

  [[3 1 1]
   [4 3 2]
   [0 1 2]]

  [[1 1 2]
   [3 2 0]
   [1 2 1]]]


 [[[0 1 2]
   [4 1 2]
   [0 1 0]]

  [[1 2 2]
   [1 2 2]
   [1 0 2]]

  [[2 2 3]
   [2 2 2]
   [0 2 3]]

  ...

  [[3 4 3]
   [4 0 1]
   [4 3 4]]

  [[4 3 2]
   [0 1 2]
   [3 4 0]]

  [[3 2 0]
   [1 2 1]
   [4 0 4]]]


 ...


 [[[1 2 0]
   [0 1 1]
   [3 0 3]]

  [[2 0 4]
   [1 1 1]
   [0 3 4]]

  [[0 4 3]
   [1 1 2]
   [3 4 2]]

  ...

  [[4 1 3]
   [2 3 1]
   [1 2 0]]

  [[1 3 3]
   [3 1 4]
   [2 0 4]]

  [[3 3 4]
   [1 4 1]
   [0 4 2]]]


 [[[0 1 1]
   [3 0 3]
   [3 0 0]]

  [[1 1 1]
   [0 3 4]
   [0 0 0]]

  [[1 1 2]
   [3 4 2]
   [0 0 4]]

  ...

  [[2

#Crear una matriz subclase 2D tal que Z[i,j]==Z[j,i]
class Symetric(np.ndarray):
    def __setitem__(self, (i,j), value):
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

In [68]:
#Considerar un conjunto de matrices p cuya forma es (n,n) y un conjunto de vectores p cuya forma es (n,1), computar la suma del producto de la matriz p de una sola vez
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes= [[0,2],[0,1]])
print(S)

[[200.]
 [200.]
 [200.]
 ...
 [200.]
 [200.]
 [200.]]


#Considerar una matriz 16x16, obtener la suma de los bloques 4x4
Z = np.ones(16,16)
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
np.arange(0, Z.shape[1], k), axis=1)

In [69]:
#Implementar el Juego de la Vida con matrices
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
    Z[1:-1,0:-2] + Z[1:-1,2:] +
    Z[2: ,0:-2] + Z[2: ,1:-1] + Z[2: ,2:])
    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)


In [70]:
#Obtener los valores mas grandes n de una matriz
Z = np.arange(10000)
n = 5
# Slow
print (Z[np.argsort(Z)[-n:]])
# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9995 9999 9998 9997 9996]


In [71]:
#Dado un numero arbitrario de vectores, construir un producto cartesiano
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:,n] = arrays[n][ix[:,n]]
    return ix

print(cartesian(([1,2,3],[4,5],[6,7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 ...
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [72]:
#Cómo crear una matriz de registros a partir de una matriz regular
Z = np.array([('Hello',2.5,3),
              ('World',3.6,2)])
R = np.core.records.fromarrays(Z.T, names='col1 , col2, col3', formats='S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#Considerar un vector grande Z, computar Z a la potencia de 3 usando tres metodos diferentes
Z = np.random.rand(5e7)
%timeit np.power(x,3)
1 loops, best of 3: 574 ms per loop
%timeit x*x*x
1 loops, best of 3: 429 ms per loop
%timeit np.einsum('i,i,i->i',x,x,x)
1 loops, best of 3: 244 ms per loop

In [73]:
#Considerar A(8,3) y B(2,2), encontrar filas de A que contienen elementos de cada fila de B sin importar el orden de los elementos
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 2 5]


In [74]:
#Considerar una matriz(10,3), extraer las filas con valores desiguales
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[0 0 0]
 [3 2 0]
 [3 1 2]
 ...
 [1 4 2]
 [2 1 2]
 [1 0 4]]
[[3 2 0]
 [3 1 2]
 [1 1 4]
 ...
 [1 4 2]
 [2 1 2]
 [1 0 4]]


In [75]:
#Convertir un vector de integros en una matriz binaria
I = np.array([0,1,2,3,15,16,32,64,128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


In [76]:
#Dada una matriz de dos dimensiones, extraer filas unicas
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 1 0]
 [1 1 0]
 [1 1 1]]


#Considerar dos vectores A & B, escribe el equivalente einsum de inner, outside, sum, y función mul
np.einsum('i->', A) # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B) # np.inner(A, B)
np.einsum('i,j', A, B) # np.outer(A, B)

In [77]:
#Considerar un patron descrito por dos vectores (X,Y), como muestrearlo usando muestras equidistantes
phi = np.arange(0,10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 #largo de los segmentos
r = np.zeros_like(x)
r[1:] = np.cumsum(dr) #patron integrado
r_int = np.linspace(0, r.max(), 200) #patron regular espaciado
x_int = np.interp(r_int, r, x) #patron integrado
y_int = np.interp(r_int, r, y)

In [78]:
#Dado un número entero n y una matriz 2D X, seleccionar de X las filas que pueden ser interpretadas como extractos de una distribución multinomial con n grados, es decir, las filas que solo contienen números enteros y que suman n
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
[2.0, 0.0, 1.0, 1.0],
[1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]
